// Ranked openings — sample data
// Top picks (tier S — apply now). Next best (tier B — worth a look).

const RANKED = {
  topPicks: [
    {
      id: "stripe-head-pricing",
      tier: "S",
      score: 94,
      role: "Head of Pricing Strategy",
      co: "Stripe",
      logo: "ST",
      brand: "#635BFF",
      loc: "San Francisco, CA",
      remote: "Remote OK",
      salary: "$200k–$260k",
      posted: "Today",
      url: "https://stripe.com/jobs",
      reason: "Maps directly to your pricing-ops experience at Square. Recruiter usually replies in 3 days.",
    },
    {
      id: "figma-director-ps",
      tier: "S",
      score: 91,
      role: "Director, Product Strategy & Operations",
      co: "Figma",
      logo: "FI",
      brand: "#A259FF",
      loc: "San Francisco, CA",
      remote: null,
      salary: "$210k–$270k",
      posted: "Today",
      url: "https://figma.com/careers",
      reason: "Hiring manager came from your alma mater. JD overlaps 7 of 8 listed responsibilities.",
    },
    {
      id: "vercel-cos",
      tier: "S",
      score: 88,
      role: "Chief of Staff to the CEO",
      co: "Vercel",
      logo: "VE",
      brand: "#C13584",
      loc: "Remote",
      remote: "Remote OK",
      salary: "$170k–$220k",
      posted: "1d ago",
      url: "https://vercel.com/careers",
      reason: "Series E, ~600 people — the stage you've said you want next.",
    },
  ],
  nextBest: [
    {
      id: "databricks-spm",
      tier: "B",
      score: 76,
      role: "Senior Pricing Manager",
      co: "Databricks",
      logo: "DA",
      brand: "#C2410C",
      loc: "San Francisco, CA",
      remote: null,
      salary: "$185k–$235k",
      posted: "2d ago",
      url: "https://databricks.com/careers",
      reason: "Strong stack overlap, one rung below the level you've been targeting.",
    },
    {
      id: "ramp-strat-fin",
      tier: "B",
      score: 73,
      role: "Strategic Finance Lead",
      co: "Ramp",
      logo: "RA",
      brand: "#F59E0B",
      loc: "New York, NY",
      remote: "Remote OK",
      salary: "$180k–$230k",
      posted: "2d ago",
      url: "https://ramp.com/careers",
      reason: "Finance-adjacent, but the team is small and the JD reads like a Chief-of-Staff role.",
    },
    {
      id: "linear-bizops",
      tier: "B",
      score: 71,
      role: "Business Operations Lead",
      co: "Linear",
      logo: "LI",
      brand: "#5E6AD2",
      loc: "Remote",
      remote: "Remote OK",
      salary: "$160k–$210k",
      posted: "3d ago",
      url: "https://linear.app/careers",
      reason: "Fully remote, generalist scope. Series C — slightly earlier than your target.",
    },
    {
      id: "notion-ps",
      tier: "B",
      score: 68,
      role: "Product Strategy Lead, AI",
      co: "Notion",
      logo: "NO",
      brand: "#14130F",
      loc: "San Francisco, CA",
      remote: null,
      salary: "$190k–$240k",
      posted: "4d ago",
      url: "https://notion.so/careers",
      reason: "AI-focused — outside your stated domain but the comp band is well within range.",
    },
    {
      id: "anthropic-cos",
      tier: "B",
      score: 65,
      role: "Chief of Staff, Go-to-Market",
      co: "Anthropic",
      logo: "AN",
      brand: "#D97757",
      loc: "San Francisco, CA",
      remote: null,
      salary: "$220k–$280k",
      posted: "5d ago",
      url: "https://anthropic.com/careers",
      reason: "On-site only. Worth it if you'd consider relocating — comp ceiling is the highest this week.",
    },
  ],
};

Object.assign(window, { RANKED });
