# HTML email builder and Gmail SMTP sender.
# Called by run_digest.py as the final step of the pipeline.
#
#   build_html(result)    renders a RankerResult into a styled HTML email string
#   send_digest(result)   calls build_html, then sends via Gmail SMTP; returns False if nothing to send

import logging
import smtplib
from datetime import datetime, timezone
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

import anthropic

from config.config import GMAIL_APP_PASSWORD, RECIPIENT_EMAIL
from src.ranker import RankedJob, RankerResult

logger = logging.getLogger(__name__)

SMTP_HOST = 'smtp.gmail.com'
SMTP_PORT = 587


def _job_card(rj: RankedJob, rank: int) -> str:
    loc = f" &middot; {rj.job.location}" if rj.job.location else ""
    source_label = "LinkedIn" if rj.job.source == "linkedin" else "Google Alerts"
    return f"""
    <tr>
      <td style="padding:12px 0;border-bottom:1px solid #eee;">
        <div style="font-size:13px;color:#888;margin-bottom:2px;">
          #{rank} &nbsp;&bull;&nbsp; {source_label}{loc}
        </div>
        <div style="font-size:16px;font-weight:600;margin-bottom:2px;">
          <a href="{rj.job.url}" style="color:#1a1a1a;text-decoration:none;">{rj.job.title}</a>
        </div>
        <div style="font-size:14px;color:#444;margin-bottom:4px;">{rj.job.company}</div>
        <div style="font-size:13px;color:#666;font-style:italic;">{rj.reason}</div>
      </td>
    </tr>"""


def _section(title: str, colour: str, jobs: list[RankedJob], start_rank: int = 1) -> str:
    if not jobs:
        return ''
    cards = ''.join(_job_card(rj, start_rank + i) for i, rj in enumerate(jobs))
    return f"""
    <h2 style="font-size:16px;font-weight:700;color:{colour};margin:28px 0 8px;">{title}</h2>
    <table width="100%" cellpadding="0" cellspacing="0" border="0">
      {cards}
    </table>"""


def build_html(result: RankerResult) -> str:
    today = datetime.now(timezone.utc).strftime("%B %d, %Y")
    total = len(result.top) + len(result.next_best)

    if result.top:
        body = _section("★ Top Options", "#1a7f37", result.top)
        body += _section("◆ Next Best", "#735c0f", result.next_best, start_rank=len(result.top) + 1)
        summary = f"{len(result.top)} top match{'es' if len(result.top) != 1 else ''}, {len(result.next_best)} worth a look"
    elif result.next_best:
        body = """<p style="color:#666;font-style:italic;margin-bottom:16px;">
            Nothing cleared the top-options bar today — here are the closest matches.</p>"""
        body += _section("◆ Next Best", "#735c0f", result.next_best)
        summary = f"No top matches today &mdash; {len(result.next_best)} next-best options"
    else:
        body = '<p style="color:#666;">No new matching jobs today.</p>'
        summary = "No new matches today"

    return f"""<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body style="margin:0;padding:0;background:#f5f5f5;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#f5f5f5;padding:24px 0;">
    <tr><td align="center">
      <table width="600" cellpadding="0" cellspacing="0" style="background:#fff;border-radius:8px;padding:32px;max-width:600px;">
        <tr><td>
          <div style="font-size:12px;color:#888;margin-bottom:4px;">{today}</div>
          <h1 style="font-size:22px;font-weight:700;margin:0 0 4px;">Job Search Digest</h1>
          <div style="font-size:14px;color:#555;margin-bottom:24px;">{summary}</div>
          {body}
          <div style="margin-top:32px;font-size:12px;color:#aaa;border-top:1px solid #eee;padding-top:16px;">
            {total} jobs surfaced &mdash; generated by your job search app
          </div>
        </td></tr>
      </table>
    </td></tr>
  </table>
</body>
</html>"""


_SUBJECT_PROMPT = """\
Write a short, punchy email subject line for a daily job search digest.

Rules:
- Must include: the date ({date}), number of top matches ({top}), number of next-best matches ({next_best})
- Tone: energetic but not cringe — like a sharp friend, not a recruiter
- One emoji max, used tastefully
- Under 70 characters
- No quotes, no explanation — just the subject line

Examples of the style (do not repeat these):
- 🎯 3 hot leads + 5 on deck — Jun 17
- Your picks for Jun 17: 3 strong, 5 decent
- Jun 17 digest — 3 worth applying, 5 to watch
"""


def _generate_subject(date: str, top: int, next_best: int) -> str:
    fallback = f"🎯 {top} hot leads + {next_best} on deck — Your job picks for {date}"
    try:
        client = anthropic.Anthropic()
        message = client.messages.create(
            model="claude-haiku-4-5-20251001",
            max_tokens=60,
            messages=[{
                "role": "user",
                "content": _SUBJECT_PROMPT.format(date=date, top=top, next_best=next_best),
            }],
        )
        return message.content[0].text.strip()
    except Exception:
        logger.warning("Failed to generate subject via Claude, using fallback")
        return fallback


def send_digest(result: RankerResult, recipient_email: str) -> bool:
    """Build and send the digest email to recipient_email. Returns True if sent, False if skipped (nothing to send)."""
    if not result.top and not result.next_best:
        logger.info("No jobs to send — skipping digest")
        return False

    if not GMAIL_APP_PASSWORD:
        raise ValueError("GMAIL_APP_PASSWORD is not set in .env")
    if not RECIPIENT_EMAIL:
        raise ValueError("RECIPIENT_EMAIL (sending account) is not set in .env")

    today = datetime.now(timezone.utc).strftime("%b %d")
    subject = _generate_subject(today, len(result.top), len(result.next_best))

    msg = MIMEMultipart('alternative')
    msg['Subject'] = subject
    msg['From'] = RECIPIENT_EMAIL
    msg['To'] = recipient_email
    msg.attach(MIMEText(build_html(result), 'html'))

    with smtplib.SMTP(SMTP_HOST, SMTP_PORT) as server:
        server.starttls()
        server.login(RECIPIENT_EMAIL, GMAIL_APP_PASSWORD.replace(' ', ''))
        server.sendmail(RECIPIENT_EMAIL, recipient_email, msg.as_string())

    logger.info(f"Digest sent to {recipient_email} ({len(result.top)} top, {len(result.next_best)} next best)")
    return True
